travis:
  secure:
    BINSTAR_TOKEN: QoFWMjxd3/xZzS0RuOZzirdkYO0tFqu3qfAeOkS/srMX/WjiwgXTNqNSxFwPuNVC7IZkHwt3otMGQ4L8Wrl+je/VgCUhxZdvOW/sP/Dyr2j7sklru5SbvAE4GsI3ICeFT5YHsZQ665CH/9ndplmGHplK9VPjHdVWF7CWQ9KFduJej7YfUiOebrYqGoHAeUfr+4szErBL3v9pDSDDS9AsnXx9X0kqAWFBzOxPNKEpY7UEIBkYvI8JxO4JpSkEuw+ll7Kp+o5Py3+KGlOjb3pUmmPncBdC4Q8Du8Z1+8/RTBEADf8jFc6kVQFP5KyPrDa/Mz4TWDAfw/oQvgrzBR56EvjZWo4XuFoIqUg+3dkbC8DhaFTovc0e1k8Rehwx2DHCuGUYJvs3zn7mSJqQp8+vpEjVvtLsBE6D9FzoTYbv+G7GBbIhm7Kw/8F2oiXZnEcu6QKD8b7r7qnG+sBDxeg17m/Cy8TB6kwM4BNzE6/nD7Jav877BtbBrjxRQDqrN0c2vecBBFHv3dUaSQODbAByypRy3nRlGJNUMjtW9p23YiVl9jv876+kxsc4Yd96OaX1uNIH1Pk9o4g8TYifFAc51eJppBXw+d5SfYT6vAvZC1OVnxWpLzvbR/0OPHFGSbOh8iRvUPix37JvHLRHTuCOrkhkSpLPBdIeSTz0cJzcK9U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
